@@ ::= <command> (@@ | <None>)
<command> ::= (<affect> | <print>) ";"
<affect> ::= identifier "=" <expr>
<comment> ::= "#" .*
<print> ::= "PRINT" <expr>;
<expr> ::= identifier | num | <add> | <sub> | <div> | <mul> | "(" <expr> ")"
<add> ::= <expr> "+" <expr>
<sub> ::= <expr> "-" <expr>
<div> ::= <expr> "/" <expr>
<mul> ::= <expr> "*" <expr>

<comment> ::= #.*

digit ::= [0-9]+
identifier ::= [a-z]+[0-9]*
int ::= digit+
float ::= digit+"."digit+
bool ::= TRUE | FALSE
